Vision tutorial
NeLy-EPFL/flygym pull request #176
Opened 2024-06-07 15:35 UTC by tkclam

### Description
Add tutorial for connectome-constrained visual model

### Types of changes

- [ ] Bugfix
- [ ] New feature
- [x] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [x] Other (explain)

### Does this address any currently open issues?
[list open issues here]

2024-06-07 15:42 UTC, sibocw commented
Thank you! I will work on this soon.

2024-06-07 16:26 UTC, sibocw requested changes
Hi Tommy, can you check the following comments, and add a paragraph in the tutorial to explain the difference between the HybridTurningController and the HybridTurningFly please?

2024-06-07 16:26 UTC, sibocw commented on flygym/examples/vision/realistic_vision_fly.py
Maybe `RealisticVisionFly` can be moved to `realistic_vision.py`?

2024-06-07 16:26 UTC, sibocw commented on flygym/examples/vision/vision_network.py
thanks for fixing this!

2024-06-07 16:26 UTC, sibocw commented on flygym/simulation.py
> +
Why would some flies not have the close method? Should we add an empty `.close()` to the fly base class then?

2024-06-07 16:26 UTC, sibocw commented on notebooks/connectome_vision_model.ipynb
Can you add a paragraph explaining the difference between HybridTurningController and HybridTurningFly?

2024-06-08 15:32 UTC, tkclam commented on notebooks/connectome_vision_model.ipynb
Shall we replace `HybridTurningController` with `HybridTurningFly` and remove `HybridTurningFly` to reduce code duplications?

2024-06-09 19:24 UTC, sibocw commented on notebooks/connectome_vision_model.ipynb
That sounds good, but probably a lot of things need to change... i'm not sure if it's worth redoing everything again...

2024-06-12 09:23 UTC, sibocw approved these changes

2024-06-12 09:23 UTC, merged