start branch for v1.2.0
NeLy-EPFL/flygym pull request #229
Opened 2024-11-16 13:20 UTC by sibocw

### Description
Main changes:
- Update FlyVision code to keep up with their stable release - @sibocw 
- Enhance camera logic (?) - @stimpfli 
- Add NeuroMechFly game for outreach (used at EPFL Scientastic! Days) - @stimpfli @Dominic-DallOsto 

### Does this address any currently open issues?
#188 #224 #228

2024-11-24 17:18 UTC, sibocw commented
Remember to check if numpy 2.* compatibility issues have been solved on upstream dependencies.

2024-12-20 09:40 UTC, Dominic-DallOsto commented
Weirdly, this works fine on every platform except macos 13, where it fails with the following errors:

```
=========================== short test summary info ============================
FAILED flygym/examples/head_stabilization/tests/test_model.py::test_torch_model - RuntimeError: Could not infer dtype of numpy.float32
FAILED flygym/examples/head_stabilization/tests/test_model.py::test_model_wrapper - RuntimeError: Could not infer dtype of numpy.float32
FAILED flygym/examples/vision/tests/test_retina_mapper.py::test_retina_mapper - RuntimeError: Numpy is not available
======= 3 failed, 37 passed, 3 skipped, 21 warnings in 628.29s (0:10:28) =======
```

On macos 13 it pulls in `numpy==2.0.2` and `torch=2.2.2` whereas on macos 14 it pulls in `numpy==2.2.0` and `torch==2.5.1` maybe that's part of the problem?

2024-12-20 14:01 UTC, Dominic-DallOsto commented
Ok, I think this fixes all the issues, except for the camera updates.

If possible it would be great to push the camera changes to a later release so we can base the game off flygym v1.2.0.

Does that sound OK?

2024-12-20 14:46 UTC, tkclam approved these changes

2024-12-20 14:46 UTC, tkclam approved these changes

2025-02-05 23:39 UTC, sibocw commented
See also #234 , which implements setting NumPy version conditioned on the system platform, but it is not merged into this version because it makes dependency graph resolution extremely slow.

2025-02-06 15:59 UTC, stimpfli commented on doc/source/tutorials/advanced_olfaction.rst
> +    from flygym.examples.olfaction.plume_tracking_arena import OdorPlumeArena
Import from flygym.examples.olfaction so  plume_tracking_arena can be removed

2025-02-06 16:27 UTC, stimpfli requested changes

2025-02-06 16:27 UTC, stimpfli commented on flygym/examples/head_stabilization/collect_training_data.py
> +    run_simulation(*job_specs[0])
Oops this should have been reverted once tested

2025-02-06 16:27 UTC, stimpfli commented on flygym/examples/olfaction/simulate_plume_dataset.py
> +            data=np.stack(smoke_hist[0:100]).astype(np.float16),
All file should be reverted

2025-02-06 16:27 UTC, stimpfli commented on flygym/examples/vision/follow_fly_closed_loop.py
> +    process_trial("flat", True, "lc910_inputs", (-5, 10))
Again this needs to be reset

2025-02-07 09:33 UTC, sibocw commented
I'm fixing the the versions of `mujoco` and `dm_control` to the latest versions as of today. Based on previous experience, new versions of the to often broke flygym due to API-breaking changes. Therefore, in the future, let's always strictly specify the version of these two (ie. with `==`). We will manually increase the versions to the latest and test flygym compatibility for each flygym release.

Also, I'm specifying dm-control 0.1.8 as 0.1.9 was breaking on @fhurtak's (Intel) and my (Apple Silicon) Macs (see #128 on their repo). For some reason this wasn't a problem on Github CI runners (see https://github.com/NeLy-EPFL/flygym/actions/runs/13183677540/job/36800522220 for an example of successful execution on macOS with dm-tree 0.1.9).

2025-02-12 16:10 UTC, Dominic-DallOsto commented on doc/source/tutorials/advanced_olfaction.rst
>  Note that we have added a bird’s eye camera for rendering.
You removed the bird's eye camera here right? Or does it now get added automatically when you create the arena? Then maybe it's better to update the description to say that?

2025-02-12 17:19 UTC, stimpfli commented on doc/source/tutorials/advanced_olfaction.rst
>  Note that we have added a bird’s eye camera for rendering.
Just removed it in [1c40fcc](https://github.com/NeLy-EPFL/flygym/pull/229/commits/1c40fcc09c2c8c517d557b3483f1e6666550cd5d)

2025-02-13 09:26 UTC, Dominic-DallOsto commented on flygym/arena/tethered.py
> +        raise NotImplementedError
If this isn't implemented, doesn't this mean that I'll get an error if I try to use the `Tethered` arena in a simulation?

From what I can tell this is just used as a subclass for other arenas that implement this method properly?

* If I should be able to actually use the `Tethered` and `Ball` arenas directly, this should be set to some value - `-inf` maybe or will that mess up the rendering?
* If I shouldn't use the `Tethered` or the `Ball` arenas directly, maybe it'd be good to add a note to the class docstring that these classes are still just mean to be abstract. And don't put this method at all here because then when trying to initialise the `Tethered` class you should get an error that it's an abstract class and the method isn't implemented

Hope that makes sense!

2025-02-13 09:33 UTC, Dominic-DallOsto commented on flygym/examples/olfaction/plume_tracking_arena.py
> +        """
For me this docstring isn't needed because you already have it for the class. Is there some case where this doesn't work and you needed to duplicate the docstring here?

2025-02-13 09:38 UTC, stimpfli commented on flygym/arena/tethered.py
> +        raise NotImplementedError
Yes this is an overlook on my side
Fixed in [91810f0](https://github.com/NeLy-EPFL/flygym/pull/229/commits/91810f063d74ff7b5111f6c4a6dd04fb2bbc6557)

2025-02-13 09:43 UTC, Dominic-DallOsto commented on flygym/examples/vision/simple_visual_taxis.py
> +        self.arena.reset(self.physics, seed=seed)
I get an error in the code checker here that `self.arena` is either of type `BaseArena` or `FlatTerrain` but neither of them have a `reset` method.

Is this correct? Or what is actually meant to be happening here?

2025-02-13 09:47 UTC, Dominic-DallOsto commented on flygym/tests/test_check_env.py
> +        else [Camera(fly.model.worldbody, "camera_left", fly.name) for fly in flies]
The code checker gives me an error here that you should pass a list of strings to `targeted_fly_names` instead of a string. I don't think `Camera` smoothly handles whether it's a string of list of strings, so I guess this should be changed to this?

`[Camera(fly.model.worldbody, "camera_left", [fly.name]) for fly in flies]`

2025-02-13 09:48 UTC, Dominic-DallOsto commented on flygym/tests/test_check_env.py
> +        else Camera(fly.model.worldbody, "camera_left", fly.name)
```suggestion
        else Camera(fly.model.worldbody, "camera_left", [fly.name])
```

2025-02-13 09:58 UTC, Dominic-DallOsto commented on flygym/simulation.py
> +                else [{}],
It seems a bit weird to have to pass in a list with an empty dict inside if there's no observation. But I don't think it's a big deal unless it's an easy fix

2025-02-13 10:11 UTC, Dominic-DallOsto commented
The outputs changed a lot in the `path_integration` notebook. Is this meant to be like this or did something break?

![image](https://github.com/user-attachments/assets/0841804e-0ed4-4598-a343-ad610e78849f)

2025-02-13 10:13 UTC, Dominic-DallOsto commented
In the `hybrid_controller` notebook, should the `init_pose` be changed to `tripod`?

![image](https://github.com/user-attachments/assets/8b2a03bc-4935-4df6-82a0-1f5d4d733a76)

2025-02-13 22:11 UTC, sibocw commented on flygym/camera.py
> +            length = np.clip(length, 1e-8, 1e8)
I'm not sure I understand - can you explain?

2025-02-13 22:14 UTC, sibocw commented on flygym/camera.py
> +# New gravity camera
removed in 0b7b893

2025-02-13 22:15 UTC, sibocw commented on flygym/examples/olfaction/plume_tracking_arena.py
> +        """
removed in b49feef

2025-02-13 22:19 UTC, sibocw commented on flygym/examples/vision/simple_visual_taxis.py
> +        self.arena.reset(self.physics, seed=seed)
It looks like Alfie added this in 4dd33b19805430fd651ecf97e4b12bf151804c22. Should this be removed @stimpfli?

2025-02-13 22:31 UTC, sibocw commented on flygym/tests/test_check_env.py
> +        else [Camera(fly.model.worldbody, "camera_left", fly.name) for fly in flies]
see #237

2025-02-13 22:31 UTC, sibocw commented on flygym/tests/test_check_env.py
> +        else Camera(fly.model.worldbody, "camera_left", fly.name)
see #237

2025-02-13 22:37 UTC, sibocw commented
> The outputs changed a lot in the `path_integration` notebook. Is this meant to be like this or did something break?
> 

Yeah it's not supposed to be like this...

2025-02-13 22:39 UTC, sibocw commented
> In the `hybrid_controller` notebook, should the `init_pose` be changed to `tripod`?
> 

Personally I think it's fine... With tripod, it's possible that the fly gets initialized in a really unfortunate/stuck position, and it wouldn't be a fair comparison. With stretched position however, the fly has to move all its legs to that position, so it's less likely that it would really get stuck in an "impossible" state.

2025-02-18 07:15 UTC, stimpfli commented on flygym/tests/test_check_env.py
> +        else [Camera(fly.model.worldbody, "camera_left", fly.name) for fly in flies]
Should be solved now

2025-02-18 07:42 UTC, stimpfli commented on flygym/simulation.py
> +                else [{}],
Solved in [c438faf](https://github.com/NeLy-EPFL/flygym/pull/229/commits/c438faf9138c1abede4ca1934fef04be0d8cb1f6)

2025-02-18 07:48 UTC, stimpfli commented
> The outputs changed a lot in the `path_integration` notebook. Is this meant to be like this or did something break?
> 
> ![image](https://private-user-images.githubusercontent.com/26859884/412836309-0841804e-0ed4-4598-a343-ad610e78849f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk4NjIyOTMsIm5iZiI6MTczOTg2MTk5MywicGF0aCI6Ii8yNjg1OTg4NC80MTI4MzYzMDktMDg0MTgwNGUtMGVkNC00NTk4LWEzNDMtYWQ2MTBlNzg4NDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE4VDA2NTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTE2NTkzYjFiMzQwZWM0ZjhiN2FiMGU2MTAxZmRkOGJjMjE4MDYyZjY4M2JhZGVmYjUwMjQ0OTc5MGZkOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0k_yc-W6jEalqrHvW-H49IdbrsvDW3WnvMuk8YLqLJo)

I do not have a local copy of the training data on my computer and reduced the size of the dataset drastically for tests. In the mean time I cleared the output but if @sibocw you want to rerun this with your local copy of the data it would probably bet better.

2025-02-18 07:50 UTC, stimpfli commented on flygym/camera.py
> +            length = np.clip(length, 1e-8, 1e8)
I guess if length is very small (what is happening most of the time) you also want to do something about it ?

2025-02-18 07:52 UTC, stimpfli commented
> In the `hybrid_controller` notebook, should the `init_pose` be changed to `tripod`?
> 
> ![image](https://private-user-images.githubusercontent.com/26859884/412837237-8b2a03bc-4935-4df6-82a0-1f5d4d733a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk4NjU0MzAsIm5iZiI6MTczOTg2NTEzMCwicGF0aCI6Ii8yNjg1OTg4NC80MTI4MzcyMzctOGIyYTAzYmMtNDkzNS00ZGY2LTgyYTAtMWY1ZDRkNzMzYTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE4VDA3NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MGUzYWExYTBjOGUzMDQ3ZDdjNDA4NmU5MTFmZGNjOWUxMTVhYzc5YzM1ODEzOTZjODg0OTM3MDcyMTg1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xl_21K3oj-LBggqsWgO4s29QU11vhKAYzgBDvt4NivA)

Fixed in [2237978](https://github.com/NeLy-EPFL/flygym/pull/229/commits/22379785f0b1fb89414479f56750f8dddf8a2377)

2025-02-18 09:32 UTC, Dominic-DallOsto commented on flygym/camera.py
> +            length = np.clip(length, 1e-8, 1e8)
Ok yeah, if the length is tiny maybe things won't be super stable so it's better just to leave the vector really small.

I just removed the clipping when the vector is huge, I think then we still want to try and normalise it to unit length then.

Hopefully that's all good!

2025-02-18 09:43 UTC, sibocw commented
> > In the `hybrid_controller` notebook, should the `init_pose` be changed to `tripod`?
> > ![image](https://private-user-images.githubusercontent.com/26859884/412837237-8b2a03bc-4935-4df6-82a0-1f5d4d733a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk4NjU0MzAsIm5iZiI6MTczOTg2NTEzMCwicGF0aCI6Ii8yNjg1OTg4NC80MTI4MzcyMzctOGIyYTAzYmMtNDkzNS00ZGY2LTgyYTAtMWY1ZDRkNzMzYTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE4VDA3NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MGUzYWExYTBjOGUzMDQ3ZDdjNDA4NmU5MTFmZGNjOWUxMTVhYzc5YzM1ODEzOTZjODg0OTM3MDcyMTg1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xl_21K3oj-LBggqsWgO4s29QU11vhKAYzgBDvt4NivA)
> 
> Fixed in [2237978](https://github.com/NeLy-EPFL/flygym/pull/229/commits/22379785f0b1fb89414479f56750f8dddf8a2377)

OK, I will do it this evening.

Do you want me to make a v1.2.0 release before COBAR today, so that students can install it already? We can make a v1.2.1 patch in the coming days when this is fixed.

2025-02-18 16:54 UTC, Dominic-DallOsto reviewed
Ok, I think we're all good on my end so whenever you're happy.

2025-02-18 16:54 UTC, Dominic-DallOsto submitted a review, later dismissed

2025-02-18 17:50 UTC, sibocw commented
Great! I will look into the path integration issue this evening and make the release. Thanks a lot for the review @Dominic-DallOsto !

2025-02-19 02:06 UTC, merged